import React from 'react'
import Head from 'next/head'
import Home from './Home'
import Header from '@/components/layout/Header'
import Carousel from '@/components/ui/Carousel'
import Campaigns from '@/components/ui/Campaigns'
import Input from '@/components/form/Input'
import Footer from '@/components/layout/Footer'

const İndex = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Home />
      <Footer />
    </div>
  )
}

export default İndex